services:
  api-server:
    build:
      context: ./shisha-log-backend/
      dockerfile: Dockerfile
    volumes:
      - ./shisha-log-backend:/app 
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - shisha
  app:
    build:
      context: ./shisha-log-frontend/
      dockerfile: Dockerfile
    volumes:
      - ./shisha-log-frontend:/src
    ports:
      - 3000:3000
    networks:
      - shisha
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./shisha-log-backend/db/init:/docker-entrypoint-initdb.d
    networks:
      - shisha
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'shisha'
      TZ: Asia/Tokyo

volumes:
  db-store:

networks:
  shisha:
    driver: bridge
